import { MetaModel } from "../meta"
import { PaginationModel } from "../pagination"

export interface GetStudent {
    meta: MetaModel
    pagination: PaginationModel
    data: GetStudentData[]
}
    
export interface GetStudentData {
    id: string
    name: string
    sex: string
    marital_status: string
    birth_regency_id: number
    birth_regency_name: string
    birth_date: string
    religion: string
    address: string
    rt: string
    rw: string
    village_id: number
    village_name: string
    district_id: number
    district_name: string
    regency_id: number
    regency_name: string
    province_id: number
    province_name: string
    country_id: number
    country_name: string
    postal_code: string
    previous_address: string
    id_number: string
    npwp_number: string
    nisn_number: string
    residence_type: string
    transportation_mean: string
    kps_receiver: string
    phone_number: string
    mobile_phone_number: string
    email: string
    homepage: string
    work_type: string
    work_place: string
    nationality: string
    askes_number: string
    total_brother: number
    total_sister: number
    hobby: string
    experience: string
    total_dependent: number
    nim_number: number
    student_force: number
    admittance_semester: string
    study_program_id: string
    study_program_name: string
    study_program_code: string
    curriculum_id: string
    curriculum_name: string
    admittance_test_number: string
    admittance_date: string
    admittance_status: string
    total_transfer_credit: string
    previous_college: string
    previous_study_program: string
    previous_nim_number: string
    previous_nim_admittance_year: string
    status: string
    is_foreign_student: boolean
    college_entrance_type: string
    class_time: string
    fund_source: string
    is_scholarship_grantee: boolean
    has_complete_requirement: boolean
    school_certificate_type: string
    school_graduation_year: string
    school_name: string
    school_accreditation: string
    school_address: string
    school_major: string
    school_certificate_number: string
    school_certificate_date: string
    total_school_final_exam_subject: string
    school_final_exam_score: number
    guardian_name: string
    guardian_birth_date: string
    guardian_death_date: string
    guardian_address: string
    guardian_regency_id: boolean
    guardian_regency_name: string
    guardian_postal_code: string
    guardian_phone_number: string
    guardian_email: string
    guardian_final_academic_background: string
    guardian_occupation: string
    father_id_number: string
    father_name: string
    father_birth_date: string
    father_death_date: string
    mother_id_number: string
    mother_name: string
    mother_birth_date: string
    mother_death_date: string
    parent_address: string
    parent_regency_id: number
    parent_regency_name: string
    parent_postal_code: string
    parent_phone_number: string
    parent_email: string
    father_final_academic_background: string
    father_occupation: string
    mother_final_academic_background: string
    mother_occupation: string
    parent_income: number
    is_financially_capable: boolean
    authentication_id: string
    authentication_is_active: boolean
    authentication_suspension_remarks: string
    dikti_study_program_code: string
}